import { useMemo, useState } from "react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { transformInvestigationToGraph, type GraphInvestigation } from "./graph-transformer";

type ThreatNodeData={label:string;type:string;severity?:string;metadata?:Record<string,unknown>};
const severityColor:Record<string,string>={CRITICAL:"#fb7185",HIGH:"#fb923c",MEDIUM:"#facc15",MODERATE:"#facc15",LOW:"#22c55e"};
function ThreatNode({data,selected}:NodeProps){const node=data as ThreatNodeData;const color=severityColor[node.severity||""]||"#22d3ee";return <div className={`min-w-40 rounded-xl border bg-slate-900 px-3 py-2 shadow-lg ${selected?"border-cyan-300 ring-2 ring-cyan-400/30":"border-slate-700"}`} style={{borderLeftColor:color,borderLeftWidth:4}}><Handle type="target" position={Position.Left} className="!bg-cyan-400"/><p className="max-w-44 truncate text-xs font-bold text-slate-100" title={node.label}>{node.label}</p><div className="mt-1 flex items-center justify-between gap-3"><span className="text-[10px] font-bold tracking-wider text-cyan-300">{node.type}</span><span className="text-[10px] font-bold" style={{color}}>{node.severity||"OBSERVED"}</span></div>{typeof node.metadata?.tactic==="string"&&<p className="mt-1 text-[10px] text-slate-400">{node.metadata.tactic}</p>}<Handle type="source" position={Position.Right} className="!bg-cyan-400"/></div>}
const nodeTypes={threat:ThreatNode};

export function ThreatGraph({investigation}:{investigation:GraphInvestigation}) {
  const {nodes:baseNodes,edges:baseEdges}=useMemo(()=>transformInvestigationToGraph(investigation),[investigation]);
  const [view,setView]=useState<"ALL"|"INFRASTRUCTURE"|"ATTACK">("ALL"); const [minimumScore,setMinimumScore]=useState(0); const [selectedId,setSelectedId]=useState<string|null>(null); const [focus,setFocus]=useState(false);
  const visibleNodes=baseNodes.filter(node=>view==="ALL"||view==="ATTACK"?view==="ALL"||String(node.data.type)==="ATTACK DNA"||String(node.data.type)==="MITRE ATT&CK":!["ATTACK DNA","MITRE ATT&CK"].includes(String(node.data.type)));
  const nodeIds=new Set(visibleNodes.map(node=>node.id)); const visibleEdges=baseEdges.filter(edge=>nodeIds.has(edge.source)&&nodeIds.has(edge.target)&&Number(edge.data?.score||0)>=minimumScore);
  const connectedIds=new Set(selectedId?visibleEdges.filter(edge=>edge.source===selectedId||edge.target===selectedId).flatMap(edge=>[edge.source,edge.target]):[]);
  const nodes=visibleNodes.map(node=>({...node,hidden:focus&&selectedId!==null&&!connectedIds.has(node.id),selected:node.id===selectedId})); const edges=visibleEdges.map(edge=>({...edge,hidden:focus&&selectedId!==null&&edge.source!==selectedId&&edge.target!==selectedId}));
  const selected=baseNodes.find(node=>node.id===selectedId) as {data:ThreatNodeData}|undefined; const evidence=baseEdges.filter(edge=>edge.source===selectedId||edge.target===selectedId);
  if(!baseNodes.length)return <div className="card text-slate-400">No related infrastructure is available for this investigation.</div>;
  return <div className="card overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 px-5 py-3"><div><p className="font-semibold">Advanced graph investigation</p><p className="text-xs text-slate-400">Select a node to inspect its evidence trail, then focus its immediate relationships.</p></div><div className="flex gap-3 text-[11px] text-slate-400"><span>{visibleNodes.length} nodes</span><span>{visibleEdges.length} relationships</span></div></div><div className="graph-investigation-controls"><label>View<select value={view} onChange={event=>{setView(event.target.value as typeof view);setSelectedId(null)}}><option value="ALL">All evidence</option><option value="INFRASTRUCTURE">Infrastructure</option><option value="ATTACK">Attack DNA & ATT&CK</option></select></label><label>Minimum confidence<select value={minimumScore} onChange={event=>setMinimumScore(Number(event.target.value))}><option value={0}>All relationships</option><option value={70}>Strong (70+)</option><option value={85}>High confidence (85+)</option></select></label><button className="text-button" disabled={!selectedId} onClick={()=>setFocus(value=>!value)}>{focus?"Show full graph":"Focus selected"}</button>{selectedId&&<button className="text-button" onClick={()=>{setSelectedId(null);setFocus(false)}}>Clear selection</button>}</div>{investigation.attackDNA?.mitreTechniques?.length?<div className="attack-graph-mitre"><b>MITRE ATT&CK</b>{investigation.attackDNA.mitreTechniques.map(technique=><span key={technique.id}>{technique.id} — {technique.name} · {technique.tactic}</span>)}</div>:null}<div className="grid lg:grid-cols-[minmax(0,1fr)_17rem]"><div className="h-[30rem]"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView minZoom={0.35} onNodeClick={(_,node)=>{setSelectedId(node.id);setFocus(false)}}><MiniMap nodeColor={node=>severityColor[String(node.data?.severity||"")]||"#22d3ee"} maskColor="rgba(2,6,23,.6)"/><Controls/><Background color="#334155" gap={22}/></ReactFlow></div><aside className="graph-evidence-panel"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Evidence inspector</p>{selected?<><h3>{String(selected.data.label)}</h3><p>{String(selected.data.type)} · {String(selected.data.severity||"OBSERVED")}</p>{typeof selected.data.metadata?.tactic==="string"&&<p>Tactic: {selected.data.metadata.tactic}</p>}<div className="graph-evidence-list"><b>Connected evidence</b>{evidence.length?evidence.map(edge=><span key={edge.id}>{edge.label} · {Number(edge.data?.score||0)} confidence</span>):<span>No direct relationship evidence.</span>}</div></>:<p className="mt-3 text-sm text-slate-400">Choose an IOC, Attack DNA, or ATT&CK node to inspect its connections.</p>}</aside></div></div>;
}
