import { useEffect, useState } from "react";
import { Activity, BookOpenCheck, FolderPlus, Keyboard, Search } from "lucide-react";
import { useNavigate } from "react-router-dom";
import type { AttackDNA, IOC, InvestigationResponse, RiskResult } from "@cybertrace/shared";
import { listIocs } from "../../services/data.api";

export function ScenarioSelector({ onSelect }: { onSelect: (value: string) => void }) {
  const items = [["Credential phishing", "login-m365-secure.test"], ["Ransomware delivery", "payload-delivery.test"], ["Command & control", "command-node.test"]] as const;
  const [selected,setSelected]=useState<string>(items[0][1]);
  const save=()=>{const cases=JSON.parse(localStorage.getItem("cybertrace-cases")||"[]") as {id:string;name:string;value:string;createdAt:string}[];localStorage.setItem("cybertrace-cases",JSON.stringify([{id:crypto.randomUUID(),name:`Investigation: ${selected}`,value:selected,createdAt:new Date().toISOString()},...cases]));window.dispatchEvent(new Event("cybertrace:cases"));};
  return <div className="scenario-row"><span>Guided demo:</span>{items.map(([label,value])=><button type="button" key={value} onClick={()=>{setSelected(value);onSelect(value)}}>{label}</button>)}<button type="button" className="case-save-button" onClick={save}><FolderPlus size={14}/> Save to case workspace</button></div>;
}
export function InvestigationTimeline({ result }: { result: InvestigationResponse }) { const points=[["Observed",result.ioc.firstSeen],["Last active",result.ioc.lastSeen],["Enriched",result.generatedAt],["Correlated",result.generatedAt]];return <section className="card"><div className="panel-title"><Activity size={17}/><div><h2>Investigation timeline</h2><p>Evidence progression for this indicator</p></div></div><ol className="timeline">{points.map(([name,date])=><li key={name}><i/><strong>{name}</strong><span>{date ? new Date(date).toLocaleString() : "No timestamp available"}</span></li>)}</ol></section>; }
export function ScoreEvidence({ risk, confidence }: { risk: RiskResult; confidence: number }) { const [open,setOpen]=useState(false);const quality=confidence>=80?"High evidence quality":confidence>=50?"Moderate evidence quality":"Limited evidence quality";return <section className="card"><div className="panel-title"><BookOpenCheck size={17}/><div><h2>Why this score?</h2><p>{quality} · {confidence}% confidence</p></div><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?"Hide evidence":"View evidence"}</button></div>{open&&<div className="evidence-drawer"><p>Risk score <b>{risk.score}/100</b> is based on the following available evidence.</p>{risk.reasons.length?<ul>{risk.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>:<p>No malicious evidence was returned. Unknown does not mean safe.</p>}<small>Score and confidence reflect the available evidence, not attribution certainty.</small></div>}</section>; }
const mitre:Record<string,{id:string;tactic:string}[]>={"Credential Phishing Cluster":[{id:"T1566",tactic:"Phishing"},{id:"T1056",tactic:"Input Capture"}],"Ransomware Infrastructure Cluster":[{id:"T1105",tactic:"Ingress Tool Transfer"},{id:"T1486",tactic:"Data Encrypted for Impact"}],"Malware Command-and-Control Cluster":[{id:"T1071",tactic:"Application Layer Protocol"},{id:"T1105",tactic:"Ingress Tool Transfer"}]};
export function MitreMapping({ attackDNA }: { attackDNA: AttackDNA | null }) { const mappings=attackDNA?mitre[attackDNA.name]||[]:[];return <section className="card"><div className="panel-title"><span className="mitre-mark">M</span><div><h2>MITRE ATT&CK mapping</h2><p>Technique references for analyst context</p></div></div>{attackDNA?<div className="mitre-list">{mappings.length?mappings.map(item=><span key={item.id}><b>{item.id}</b>{item.tactic}</span>):<p>No static reference mapping is available for this profile.</p>}</div>:<p className="text-sm text-slate-400">A correlated Attack DNA profile is needed before mapping techniques.</p>}</section>; }
export function SaveCase({ result }: { result: InvestigationResponse }) { const save=()=>{const cases=JSON.parse(localStorage.getItem("cybertrace-cases")||"[]") as {id:string;name:string;value:string;createdAt:string}[];const entry={id:crypto.randomUUID(),name:`Investigation: ${result.ioc.value}`,value:result.ioc.value,createdAt:new Date().toISOString()};localStorage.setItem("cybertrace-cases",JSON.stringify([entry,...cases]));window.dispatchEvent(new Event("cybertrace:cases"));};return <button className="btn btn-quiet" onClick={save}><FolderPlus size={16}/> Save to case workspace</button>; }
export function CaseWorkspacePage(){const [cases,setCases]=useState<{id:string;name:string;value:string;createdAt:string}[]>([]);useEffect(()=>{const load=()=>setCases(JSON.parse(localStorage.getItem("cybertrace-cases")||"[]"));load();window.addEventListener("cybertrace:cases",load);return()=>window.removeEventListener("cybertrace:cases",load)},[]);return <><div className="mb-6"><h1 className="text-2xl font-bold">Case workspace</h1><p className="text-sm text-slate-400">Saved investigations on this browser.</p></div><div className="card">{cases.length?<div className="space-y-3">{cases.map(item=><div className="case-item" key={item.id}><div><strong>{item.name}</strong><p>{new Date(item.createdAt).toLocaleString()}</p></div><span>{item.value}</span></div>)}</div>:<p className="text-slate-400">Save an investigation to begin a local case workspace.</p>}</div></>}
export function ComparisonPage(){const [items,setItems]=useState<IOC[]>([]);const [left,setLeft]=useState("");const [right,setRight]=useState("");useEffect(()=>{listIocs("").then(x=>{setItems(x.items);setLeft(x.items[0]?.id||"");setRight(x.items[1]?.id||"")})},[]);const select=(value:string,onChange:(v:string)=>void)=><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{items.map(item=><option value={item.id} key={item.id}>{item.value}</option>)}</select>;const a=items.find(x=>x.id===left),b=items.find(x=>x.id===right);return <><div className="mb-6"><h1 className="text-2xl font-bold">IOC comparison</h1><p className="text-sm text-slate-400">Compare evidence quality and risk across two stored indicators.</p></div><div className="grid gap-4 md:grid-cols-2">{select(left,setLeft)}{select(right,setRight)}</div><div className="mt-5 grid gap-5 md:grid-cols-2">{[a,b].map(item=><div className="card" key={item?.id}>{item?<><p className="text-sm text-cyan-300">{item.type}</p><h2 className="mt-2 break-all text-lg font-semibold">{item.value}</h2><dl className="comparison-list"><div><dt>Risk score</dt><dd>{item.riskScore}/100</dd></div><div><dt>Confidence</dt><dd>{item.confidence}%</dd></div><div><dt>Reputation</dt><dd>{item.reputation}</dd></div><div><dt>Evidence sources</dt><dd>{item.sources.length}</dd></div></dl></>:"Loading indicators…"}</div>)}</div></>}
export function CommandPalette(){const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const nav=useNavigate();useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(value=>!value)}if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);if(!open)return null;const go=(path:string)=>{nav(path);setOpen(false)};return <div className="command-backdrop" role="dialog" aria-modal="true" aria-label="Command palette"><div className="command-palette"><div><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Investigate an IOC or navigate…" onKeyDown={e=>{if(e.key==="Enter"&&query.trim())go(`/investigate?ioc=${encodeURIComponent(query.trim())}`)}}/></div><button onClick={()=>go("/investigate")}>Investigate indicator</button><button onClick={()=>go("/compare")}>Compare IOCs</button><button onClick={()=>go("/cases")}>Open case workspace</button><small><Keyboard size={13}/> Ctrl K to open · Esc to close</small></div></div>}
