import { useEffect, useState } from "react";
import { Activity, BookOpenCheck, FolderPlus, Keyboard, Search } from "lucide-react";
import { useNavigate } from "react-router-dom";
import type { AttackDNA, IOC, InvestigationResponse, InvestigationTimeline as InvestigationTimelineData, RiskResult } from "@cybertrace/shared";
import { createCase, listIocs } from "../../services/data.api";

export function ScenarioSelector({ onSelect }: { onSelect: (value: string) => void }) {
  const items = [["Credential phishing", "login-m365-secure.test"], ["Ransomware delivery", "payload-delivery.test"], ["Command & control", "command-node.test"]] as const;
  const [selected,setSelected]=useState<string>(items[0][1]);
  return <div className="scenario-row"><span>Guided demo:</span>{items.map(([label,value])=><button type="button" key={value} onClick={()=>{setSelected(value);onSelect(value)}}>{label}</button>)}</div>;
}
export function InvestigationTimeline({ timeline }: { timeline: InvestigationTimelineData | null }) { const [visible,setVisible]=useState(0);useEffect(()=>{setVisible(0);if(!timeline)return;const timers=timeline.events.map((_,index)=>window.setTimeout(()=>setVisible(index+1),180+index*240));return()=>timers.forEach(window.clearTimeout);},[timeline?.id,timeline?.events.length]);if(!timeline)return null;return <section className="card investigation-timeline"><div className="panel-title"><Activity size={17}/><div><h2>Investigation timeline</h2><p>Persisted activity for this investigation</p></div><span className="timeline-live"><i/> Live</span></div><ol className="timeline" aria-live="polite">{timeline.events.slice(0,visible).map(event=><li key={event.id}><time>{new Date(event.occurredAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><i/><strong>{event.message}</strong></li>)}</ol></section>; }
export function ScoreEvidence({ risk, confidence }: { risk: RiskResult; confidence: number }) { const [open,setOpen]=useState(false);const quality=confidence>=80?"High evidence quality":confidence>=50?"Moderate evidence quality":"Limited evidence quality";return <section className="card"><div className="panel-title"><BookOpenCheck size={17}/><div><h2>Why this score?</h2><p>{quality} · {confidence}% confidence</p></div><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?"Hide evidence":"View evidence"}</button></div>{open&&<div className="evidence-drawer"><p>Risk score <b>{risk.score}/100</b> is based on the following available evidence.</p>{risk.reasons.length?<ul>{risk.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>:<p>No malicious evidence was returned. Unknown does not mean safe.</p>}<small>Score and confidence reflect the available evidence, not attribution certainty.</small></div>}</section>; }
export function MitreMapping({ attackDNA }: { attackDNA: AttackDNA | null }) { const mappings=attackDNA?.mitreTechniques||[];const tactics=[...new Set(mappings.map(item=>item.tactic))];return <section className="card"><div className="panel-title"><span className="mitre-mark">M</span><div><h2>MITRE ATT&CK</h2><p>Local technique mapping for this Attack DNA profile</p></div></div>{attackDNA?<>{mappings.length?<><div className="mitre-list">{mappings.map(item=><span key={item.id} title={item.description}><b>{item.id}</b><em>{item.name}</em><small>{item.tactic}</small></span>)}</div><div className="mt-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Tactics</p><div className="mitre-tactics">{tactics.map(tactic=><span key={tactic}>{tactic}</span>)}</div></div></>:<p className="mt-4 text-sm text-slate-400">No local ATT&CK mapping is available for this profile.</p>}</>:<p className="text-sm text-slate-400">A correlated Attack DNA profile is needed before mapping techniques.</p>}</section>; }
export function SaveCase({ result }: { result: InvestigationResponse }) { const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const save=async()=>{setBusy(true);setMessage("");try{await createCase(result.ioc.id);setMessage("Case saved to your workspace.");}catch(error){setMessage(error instanceof Error?error.message:"Could not save the case.");}finally{setBusy(false);}};return <div className="flex items-center gap-3"><button className="btn btn-quiet" disabled={busy} onClick={save}><FolderPlus size={16}/>{busy?"Saving…":"Save to case workspace"}</button>{message&&<span className="text-sm text-cyan-200">{message}</span>}</div>; }
export function ComparisonPage(){const [items,setItems]=useState<IOC[]>([]);const [left,setLeft]=useState("");const [right,setRight]=useState("");useEffect(()=>{listIocs("").then(x=>{setItems(x.items);setLeft(x.items[0]?.id||"");setRight(x.items[1]?.id||"")})},[]);const select=(value:string,onChange:(v:string)=>void)=><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{items.map(item=><option value={item.id} key={item.id}>{item.value}</option>)}</select>;const a=items.find(x=>x.id===left),b=items.find(x=>x.id===right);return <><div className="mb-6"><h1 className="text-2xl font-bold">IOC comparison</h1><p className="text-sm text-slate-400">Compare evidence quality and risk across two stored indicators.</p></div><div className="grid gap-4 md:grid-cols-2">{select(left,setLeft)}{select(right,setRight)}</div><div className="mt-5 grid gap-5 md:grid-cols-2">{[a,b].map(item=><div className="card" key={item?.id}>{item?<><p className="text-sm text-cyan-300">{item.type}</p><h2 className="mt-2 break-all text-lg font-semibold">{item.value}</h2><dl className="comparison-list"><div><dt>Risk score</dt><dd>{item.riskScore}/100</dd></div><div><dt>Confidence</dt><dd>{item.confidence}%</dd></div><div><dt>Reputation</dt><dd>{item.reputation}</dd></div><div><dt>Evidence sources</dt><dd>{item.sources.length}</dd></div></dl></>:"Loading indicators…"}</div>)}</div></>}
export function CommandPalette(){const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const nav=useNavigate();useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(value=>!value)}if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);if(!open)return null;const go=(path:string)=>{nav(path);setOpen(false)};return <div className="command-backdrop" role="dialog" aria-modal="true" aria-label="Command palette"><div className="command-palette"><div><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Investigate an IOC or navigate…" onKeyDown={e=>{if(e.key==="Enter"&&query.trim())go(`/investigate?ioc=${encodeURIComponent(query.trim())}`)}}/></div><button onClick={()=>go("/investigate")}>Investigate indicator</button><button onClick={()=>go("/compare")}>Compare IOCs</button><button onClick={()=>go("/cases")}>Open case workspace</button><small><Keyboard size={13}/> Ctrl K to open · Esc to close</small></div></div>}
