import { api } from "./api-client"; import type { AttackDNA, CaseStatus, CaseVerdict, DashboardStats, IOC, InvestigationCase, InvestigationResponse, InvestigationTimeline, IOCRelationship, Report, ThreatLocation } from "@cybertrace/shared";
export const dashboard=()=>api<DashboardStats>("/dashboard/stats");
export const listIocs=(query:string)=>api<{items:IOC[];pagination:{page:number;limit:number;total:number}}>(`/iocs?search=${encodeURIComponent(query)}`);
export const getIoc=(id:string)=>api<IOC>(`/iocs/${id}`); export const relations=(id:string)=>api<IOCRelationship[]>(`/iocs/${id}/relationships`);
export const investigate=(value:string)=>api<InvestigationResponse>("/iocs/search",{method:"POST",body:JSON.stringify({value})});
export const attackDna=()=>api<AttackDNA[]>("/attack-dna"); export const mapThreats=()=>api<ThreatLocation[]>("/map/threats");
export const reports=()=>api<Report[]>("/reports"); export const report=(iocId:string,investigationId?:string)=>api<Report>("/reports",{method:"POST",body:JSON.stringify({iocId,...(investigationId?{investigationId}:{})})}); export const timeline=(id:string)=>api<InvestigationTimeline>(`/investigations/${id}/timeline`);
export const cases=()=>api<InvestigationCase[]>("/cases");
export const createCase=(iocId:string,title?:string)=>api<InvestigationCase>("/cases",{method:"POST",body:JSON.stringify({iocId,...(title?{title}:{})})});
export const updateCase=(id:string,updates:{title?:string;status?:CaseStatus;verdict?:CaseVerdict;notes?:string})=>api<InvestigationCase>(`/cases/${id}`,{method:"PATCH",body:JSON.stringify(updates)});
