import { IOCType, Prisma, Reputation } from "@prisma/client";
import { prisma } from "../config/prisma";
import { mitreByAttackProfile } from "../data/mitre-attack";
import { detectIocType } from "../utils/detect-ioc-type";
import { normalizeIoc } from "../utils/normalize-ioc";
import { enrichLiveIoc } from "./enrichment.service";
import { calculateRiskScore } from "./risk.service";

const CACHE_MS=15*60_000;
const include={outgoingRelationships:{include:{targetIOC:true}},incomingRelationships:{include:{sourceIOC:true}},attackProfiles:{include:{attackProfile:{include:{iocs:{include:{ioc:true}},techniques:{include:{technique:true}}}}}},locations:{include:{location:true}}} as const;
const iocSummary=(ioc:any)=>({id:ioc.id,type:ioc.type,value:ioc.value,severity:ioc.severity,riskScore:ioc.riskScore,confidence:ioc.confidence,reputation:ioc.reputation,country:ioc.country,countryCode:ioc.countryCode,latitude:ioc.latitude,longitude:ioc.longitude,asn:ioc.asn,sources:ioc.sources,firstSeen:ioc.firstSeen,lastSeen:ioc.lastSeen,malwareAssociated:ioc.malwareAssociated,campaignAssociated:ioc.campaignAssociated,isDemo:ioc.isDemo});
const profileView=(profile:any)=>({id:profile.id,name:profile.name,attackType:profile.attackType,severity:profile.severity,confidence:profile.confidence,description:profile.description,techniques:profile.techniques.map((x:any)=>({id:x.technique.id,name:x.technique.name,description:x.technique.description})),mitreTechniques:mitreByAttackProfile[profile.name]??[],iocs:profile.iocs.map((x:any)=>iocSummary(x.ioc)),stats:profile.iocs.reduce((s:any,x:any)=>{s[`${x.ioc.type.toLowerCase()}s`]=(s[`${x.ioc.type.toLowerCase()}s`]||0)+1;return s;},{ips:0,domains:0,urls:0,hashes:0}),explanations:profile.isDemo?["Synthetic DEMO_SEED Attack DNA, based on stored relationships and techniques."]:[]});
const isDemo=(ioc:any)=>Boolean(ioc?.isDemo||ioc?.sources?.includes("DEMO_SEED"));
const related=(ioc:any)=>[...ioc.outgoingRelationships.map((r:any)=>({...r,target:iocSummary(r.targetIOC)})),...ioc.incomingRelationships.map((r:any)=>({...r,source:iocSummary(r.sourceIOC)}))].map((r:any)=>({...r,strength:r.score<40?"WEAK":r.score<70?"POSSIBLE":"STRONG"}));

export async function investigate(value:string,userId?:string,options:{refresh?:boolean}={}){
  const type=detectIocType(value);if(!type)throw Object.assign(new Error("Invalid IOC format."),{status:400,code:"INVALID_IOC"});const normalized=normalizeIoc(value);let ioc=await prisma.iOC.findUnique({where:{value:normalized},include});
  const demo=isDemo(ioc);let providers:any[]=[];let warnings:string[]=[];let dataMode:"DEMO"|"LIVE"=demo?"DEMO":"LIVE";
  if(demo){providers=[{provider:"DEMO_SEED",status:"SUCCESS",reputation:ioc!.reputation,confidence:ioc!.confidence,tags:[],warnings:[]}];}
  else {const fresh=Boolean(ioc&&Date.now()-ioc.updatedAt.getTime()<CACHE_MS&&!options.refresh);if(fresh){providers=[{provider:"Cached intelligence",status:"SUCCESS",reputation:ioc!.reputation,confidence:ioc!.confidence,tags:[],warnings:["Stored live intelligence reused (15-minute cache)."]}];warnings=["Live intelligence may be stale; use Refresh Intelligence to request current provider data."];}else{const enrichment=await enrichLiveIoc(normalized,type);providers=enrichment.providers;warnings=enrichment.warnings;const risk=calculateRiskScore({reputation:enrichment.reputation,sourceCount:enrichment.sources.length,recentActivity:Boolean(enrichment.lastSeen&&Date.now()-enrichment.lastSeen.getTime()<90*86400000),malwareAssociated:enrichment.malwareAssociated,campaignAssociated:enrichment.campaignAssociated});ioc=await prisma.iOC.upsert({where:{value:normalized},create:{value:normalized,type:type as IOCType,severity:risk.severity,riskScore:risk.score,confidence:enrichment.confidence,reputation:enrichment.reputation as Reputation,sources:enrichment.sources,firstSeen:enrichment.firstSeen,lastSeen:enrichment.lastSeen,malwareAssociated:enrichment.malwareAssociated,campaignAssociated:enrichment.campaignAssociated,country:enrichment.location?.country,countryCode:enrichment.location?.countryCode,latitude:enrichment.location?.latitude,longitude:enrichment.location?.longitude,asn:enrichment.location?.asn},update:{severity:risk.severity,riskScore:risk.score,confidence:enrichment.confidence,reputation:enrichment.reputation as Reputation,sources:enrichment.sources,firstSeen:enrichment.firstSeen,lastSeen:enrichment.lastSeen,malwareAssociated:enrichment.malwareAssociated,campaignAssociated:enrichment.campaignAssociated,country:enrichment.location?.country??undefined,countryCode:enrichment.location?.countryCode??undefined,latitude:enrichment.location?.latitude??undefined,longitude:enrichment.location?.longitude??undefined,asn:enrichment.location?.asn??undefined},include});}}
  if(!ioc){const risk=calculateRiskScore({reputation:"UNKNOWN",sourceCount:0,recentActivity:false,malwareAssociated:false,campaignAssociated:false});ioc=await prisma.iOC.create({data:{value:normalized,type:type as IOCType,severity:risk.severity,riskScore:risk.score,confidence:0,reputation:Reputation.UNKNOWN,sources:[]},include});}
  const relationships=related(ioc);const attackDNA=demo&&ioc.attackProfiles[0]?.attackProfile?profileView(ioc.attackProfiles[0].attackProfile):null;const locations=ioc.locations.map((x:any)=>({id:x.location.id,country:x.location.country,countryCode:x.location.countryCode,latitude:x.location.latitude,longitude:x.location.longitude,threatCount:1,criticalCount:ioc.severity==="CRITICAL"?1:0,iocIds:[ioc.id]}));if(!locations.length&&ioc.latitude!==null&&ioc.longitude!==null&&ioc.country){locations.push({id:`ioc-${ioc.id}`,country:ioc.country,countryCode:ioc.countryCode??undefined,latitude:ioc.latitude,longitude:ioc.longitude,threatCount:1,criticalCount:ioc.severity==="CRITICAL"?1:0,iocIds:[ioc.id]});}
  const nodes=[{id:ioc.id,label:ioc.value,type:ioc.type,severity:ioc.severity,metadata:{isDemo:demo}},...relationships.flatMap((r:any)=>r.target?[{id:r.target.id,label:r.target.value,type:r.target.type,severity:r.target.severity,metadata:{}}]:r.source?[{id:r.source.id,label:r.source.value,type:r.source.type,severity:r.source.severity,metadata:{}}]:[])];const edges=relationships.map((r:any)=>({id:r.id,source:r.sourceIocId,target:r.targetIocId,label:r.relationshipType,score:r.score}));const risk=calculateRiskScore({reputation:ioc.reputation,sourceCount:ioc.sources.length,recentActivity:!!ioc.lastSeen&&Date.now()-ioc.lastSeen.getTime()<90*86400000,malwareAssociated:ioc.malwareAssociated,campaignAssociated:ioc.campaignAssociated});
  if(ioc.reputation==="MALICIOUS"){const names=providers.filter(provider=>provider.status==="SUCCESS"&&provider.reputation==="MALICIOUS").map(provider=>provider.provider);if(names.length)risk.reasons[0]=`Malicious reputation reported by ${names.join(", ")} (+30)`;}if(ioc.sources.length>=2)risk.reasons[1]=`Malicious activity corroborated by ${ioc.sources.length} intelligence sources (+20)`;
  const messages=["IOC submitted",`${dataMode==="DEMO"?"Demo evidence":"Live intelligence"} enrichment completed`,`Risk score calculated: ${risk.score}`,`${relationships.length} related IOC${relationships.length===1?"":"s"} found`,relationships.some((relationship:any)=>relationship.strength==="STRONG")?"Strong relationship detected":"No strong relationship detected",attackDNA?"Attack DNA generated":"Attack DNA unavailable — limited evidence",locations.length?"Infrastructure mapped":"No associated infrastructure mapped"];
  const startedAt=new Date();const savedTimeline=userId?await prisma.investigation.create({data:{userId,iocId:ioc.id,query:value,events:{create:messages.map((message,sequence)=>({message,sequence,occurredAt:new Date(startedAt.getTime()+sequence*650)}))}},include:{events:{orderBy:{sequence:"asc"}}}}):null;const timeline=savedTimeline?{id:savedTimeline.id,createdAt:savedTimeline.createdAt.toISOString(),events:savedTimeline.events.map(event=>({id:event.id,sequence:event.sequence,message:event.message,occurredAt:event.occurredAt.toISOString()}))}:null;
  const queriedProviders=providers.filter(provider=>provider.status!=="SKIPPED").length;const successfulProviders=providers.filter(provider=>provider.status==="SUCCESS").length;const summary=dataMode==="DEMO"?"Synthetic seeded evidence.":`${successfulProviders} of ${queriedProviders} queried threat-intelligence providers returned relevant evidence.`;
  const finalWarnings=[...new Set([...warnings,...(demo?["Synthetic demo data only; infrastructure location is not attacker attribution."]:["External intelligence may contain stale data or false positives.","IP geolocation represents associated infrastructure and not attacker location."])])];
  return {query:value,generatedAt:new Date().toISOString(),dataMode,ioc:iocSummary(ioc),enrichment:{providers,successfulProviders,queriedProviders,summary},risk,relationships,attackDNA,graph:{nodes:Array.from(new Map(nodes.map(node=>[node.id,node])).values()),edges},locations,timeline,warnings:finalWarnings};
}
export async function getInvestigationTimeline(userId:string,id:string){const timeline=await prisma.investigation.findFirst({where:{id,userId},include:{events:{orderBy:{sequence:"asc"}}}});if(!timeline)throw Object.assign(new Error("Investigation timeline not found."),{status:404,code:"NOT_FOUND"});return {id:timeline.id,createdAt:timeline.createdAt.toISOString(),events:timeline.events.map(event=>({id:event.id,sequence:event.sequence,message:event.message,occurredAt:event.occurredAt.toISOString()}))};}
export async function addTimelineEvent(userId:string,investigationId:string,message:string){const timeline=await prisma.investigation.findFirst({where:{id:investigationId,userId},include:{events:{select:{sequence:true},orderBy:{sequence:"desc"},take:1}}});if(!timeline)throw Object.assign(new Error("Investigation timeline not found."),{status:404,code:"NOT_FOUND"});const event=await prisma.investigationTimelineEvent.create({data:{investigationId,sequence:(timeline.events[0]?.sequence??-1)+1,message}});return {id:event.id,sequence:event.sequence,message:event.message,occurredAt:event.occurredAt.toISOString()};}
export async function listIocs(query:{search?:string;type?:IOCType;severity?:any;skip:number;take:number}){const where:Prisma.IOCWhereInput={};if(query.search)where.value={contains:query.search,mode:"insensitive"};if(query.type)where.type=query.type;if(query.severity)where.severity=query.severity;const [items,total]=await prisma.$transaction([prisma.iOC.findMany({where,skip:query.skip,take:query.take,orderBy:{updatedAt:"desc"}}),prisma.iOC.count({where})]);return {items:items.map(iocSummary),pagination:{page:query.skip/query.take+1,limit:query.take,total}};}
