import { env } from "../config/env";
import type { ProviderResult } from "./provider.types";
import { providerError, skipped } from "./provider.types";

const endpointFor=(value:string,type:string)=>{const kind=type==="IP"?(value.includes(":")?"IPv6":"IPv4"):type==="DOMAIN"?"domain":type==="URL"?"url":type==="HASH"?"file":null;return kind?`https://otx.alienvault.com/api/v1/indicators/${kind}/${encodeURIComponent(value)}/general`:null;};

export async function queryOtx(value:string,type:string):Promise<ProviderResult>{
  if(!env.externalEnrichment)return skipped("AlienVault OTX","External enrichment is disabled.");
  if(!env.otxApiKey)return skipped("AlienVault OTX","OTX API key is not configured.");
  const endpoint=endpointFor(value,type);if(!endpoint)return skipped("AlienVault OTX",`OTX does not support ${type} lookups.`);
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);
  try{const response=await fetch(endpoint,{headers:{"X-OTX-API-KEY":env.otxApiKey,Accept:"application/json"},signal:controller.signal});if(response.status===429)return {provider:"AlienVault OTX",status:"RATE_LIMITED",warnings:["AlienVault OTX rate limit reached."]};if(response.status===401||response.status===403)return {provider:"AlienVault OTX",status:"ERROR",warnings:["AlienVault OTX rejected the configured API key."]};if(response.status===404)return {provider:"AlienVault OTX",status:"NO_DATA",reputation:"UNKNOWN",warnings:[]};if(!response.ok)return {provider:"AlienVault OTX",status:"ERROR",warnings:[`AlienVault OTX returned HTTP ${response.status}.`]};const data=await response.json() as {pulse_info?:{pulses?:unknown[]}};const pulses=(Array.isArray(data.pulse_info?.pulses)?data.pulse_info.pulses:[]).filter((pulse):pulse is {id?:unknown;tags?:unknown;created?:unknown;modified?:unknown}=>typeof pulse==="object"&&pulse!==null);if(!pulses.length)return {provider:"AlienVault OTX",status:"NO_DATA",reputation:"UNKNOWN",warnings:[]};const tags=[...new Set(pulses.flatMap(pulse=>Array.isArray(pulse.tags)?pulse.tags:[]).filter((tag):tag is string=>typeof tag==="string"))].slice(0,12);const firstSeen=pulses.map(pulse=>pulse.created).filter((date):date is string=>typeof date==="string").sort()[0]??null;const lastSeen=pulses.map(pulse=>pulse.modified).filter((date):date is string=>typeof date==="string").sort().at(-1)??null;const references=pulses.map(pulse=>typeof pulse.id==="string"?`https://otx.alienvault.com/pulse/${pulse.id}`:null).filter((reference):reference is string=>Boolean(reference));return {provider:"AlienVault OTX",status:"SUCCESS",reputation:"SUSPICIOUS",confidence:Math.min(75,45+pulses.length*5),campaignAssociated:pulses.length>1,tags,firstSeen,lastSeen,references,evidence:[`${pulses.length} OTX pulse${pulses.length===1?"":"s"} reference this indicator.`],warnings:[]};}catch(error){return providerError("AlienVault OTX",error);}finally{clearTimeout(timer);}
}
