import { UserPlus, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";
import { api } from "../services/api-client";
import type { UserRole } from "../utils/storage";

type ManagedUser = { id: string; name: string; email: string; role: UserRole; createdAt: string };
const roles: UserRole[] = ["ADMIN", "ANALYST", "VIEWER"];

export function AdminAccessManagementPage() {
  const { session } = useAuth(); const [users, setUsers] = useState<ManagedUser[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [member, setMember] = useState({ name: "", email: "", password: "", role: "ANALYST" as UserRole });
  const load = () => api<ManagedUser[]>("/admin/users").then(setUsers).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load users.")).finally(() => setLoading(false));
  useEffect(() => { if (session?.user.role === "ADMIN") void load(); }, [session?.user.role]);
  if (session?.user.role !== "ADMIN") return <Navigate to="/dashboard" replace />;
  const addMember = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setNotice(""); setSaving(true); try { const created = await api<ManagedUser>("/admin/users", { method: "POST", body: JSON.stringify(member) }); setUsers(current => [created, ...current]); setMember({ name: "", email: "", password: "", role: "ANALYST" }); setNotice(`${created.name} was added as ${created.role}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add member."); } finally { setSaving(false); } };
  const setRole = async (id: string, role: UserRole) => { setError(""); setNotice(""); try { const updated = await api<ManagedUser>(`/admin/users/${id}/role`, { method: "PATCH", body: JSON.stringify({ role }) }); setUsers(current => current.map(user => user.id === id ? updated : user)); setNotice(`${updated.name}'s role is now ${updated.role}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to change role."); } };
  return <section><div className="mb-6 flex items-start gap-3"><div className="brand-icon"><Users size={18} /></div><div><p className="eyebrow">Administrator only</p><h1 className="m-0 text-2xl font-semibold text-slate-100">Access management</h1><p className="mt-1 text-sm text-slate-400">Add members and manage their effective CyberTrace role.</p></div></div>{error && <p className="auth-error mb-5" role="alert">{error}</p>}{notice && <p className="mb-5 rounded-md border border-emerald-800 bg-emerald-950/50 p-3 text-sm text-emerald-200" role="status">{notice}</p>}<div className="card mb-6"><div className="mb-4 flex items-center gap-2"><UserPlus size={18} className="text-cyan-300" /><h2 className="m-0 text-base font-semibold text-slate-100">Add member</h2></div><form onSubmit={addMember} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="label">Name<input className="input" value={member.name} onChange={event => setMember({ ...member, name: event.target.value })} minLength={2} required /></label><label className="label">Email<input className="input" type="email" value={member.email} onChange={event => setMember({ ...member, email: event.target.value })} required /></label><label className="label">Temporary password<input className="input" type="password" value={member.password} onChange={event => setMember({ ...member, password: event.target.value })} minLength={8} required /></label><label className="label">Role<select className="input" value={member.role} onChange={event => setMember({ ...member, role: event.target.value as UserRole })}>{roles.map(role => <option key={role}>{role}</option>)}</select></label><button className="btn md:col-span-2 xl:col-span-4 xl:justify-self-start" disabled={saving}>{saving ? "Adding member…" : "Add member"}</button></form></div><div className="card overflow-x-auto">{loading ? <p className="text-sm text-slate-400">Loading users…</p> : <table className="table"><thead><tr><th>Member</th><th>Role</th><th>Joined</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong className="block text-slate-100">{user.name}</strong><span className="text-xs text-slate-400">{user.email}</span></td><td><label className="sr-only" htmlFor={`role-${user.id}`}>Role for {user.name}</label><select id={`role-${user.id}`} className="rounded-md border border-cyan-900 bg-cyan-950 px-2 py-1 text-xs font-semibold text-cyan-200" value={user.role} onChange={event => void setRole(user.id, event.target.value as UserRole)}>{roles.map(role => <option key={role}>{role}</option>)}</select></td><td className="whitespace-nowrap text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>}</div><p className="mt-4 text-xs text-slate-500">Only administrators can add members or change roles. You cannot remove your own administrator access.</p></section>;
}
